-- CreateIndex (CONCURRENTLY)
-- INCLUDE covers the per-consumer aggregate (agentek-console organization-accounts, part F): index-only
-- scan answers GROUP BY "user"/end_user/api_key, SUM(spend)/SUM(total_tokens) without a heap fetch.
-- Prisma's DSL can't express INCLUDE, so this column list is hand-added after `run_migration.py`
-- generated the base (team_id, startTime) index.
--
-- Disclaimer:
-- - CREATE INDEX CONCURRENTLY cannot run inside a transaction. This migration must stay a
--   single statement so Prisma Migrate on PostgreSQL can apply it outside a transaction — a plain
--   CREATE INDEX would hold a lock that blocks writes to "LiteLLM_SpendLogs" for the whole build,
--   and that table is actively written on every completion while Hermes/LiteLLM must stay up.
-- - Builds are slower and use more I/O than a blocking CREATE INDEX; if the build is
--   interrupted, Postgres may leave an INVALID index that must be dropped and recreated.
-- - Do not edit this file after it has been applied to any database: Prisma checksums
--   migrations; add a new migration instead.
-- - Requires PostgreSQL that supports CONCURRENTLY with IF NOT EXISTS (use a new migration
--   without IF NOT EXISTS if you must support older versions).
CREATE INDEX CONCURRENTLY IF NOT EXISTS "LiteLLM_SpendLogs_team_id_startTime_idx" ON "LiteLLM_SpendLogs"("team_id", "startTime")
  INCLUDE (spend, total_tokens, "user", end_user, api_key);
